/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  HTTPValidationError,
  PoemV1CreateRequest,
  PoemV2CreateRequest,
  PoemV3CreateRequest,
  PoemV4CreateRequest,
} from "./model";

/**
 * @summary Root
 */
export const rootGet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.get(`/`, options);
};

export const getRootGetQueryKey = () => {
  return [`/`] as const;
};

export const getRootGetQueryOptions = <
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getRootGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({
    signal,
  }) => rootGet({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof rootGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RootGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof rootGet>>
>;
export type RootGetQueryError = AxiosError<unknown>;

export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rootGet>>,
          TError,
          Awaited<ReturnType<typeof rootGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Root
 */

export function useRootGet<
  TData = Awaited<ReturnType<typeof rootGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getRootGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Generatepoemv1
 */
export const generatePoemV1GeneratePoemV1Post = (
  poemV1CreateRequest: PoemV1CreateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(`/generate-poem-v1`, poemV1CreateRequest, options);
};

export const getGeneratePoemV1GeneratePoemV1PostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generatePoemV1GeneratePoemV1Post>>,
    TError,
    { data: PoemV1CreateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generatePoemV1GeneratePoemV1Post>>,
  TError,
  { data: PoemV1CreateRequest },
  TContext
> => {
  const mutationKey = ["generatePoemV1GeneratePoemV1Post"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generatePoemV1GeneratePoemV1Post>>,
    { data: PoemV1CreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return generatePoemV1GeneratePoemV1Post(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GeneratePoemV1GeneratePoemV1PostMutationResult = NonNullable<
  Awaited<ReturnType<typeof generatePoemV1GeneratePoemV1Post>>
>;
export type GeneratePoemV1GeneratePoemV1PostMutationBody = PoemV1CreateRequest;
export type GeneratePoemV1GeneratePoemV1PostMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Generatepoemv1
 */
export const useGeneratePoemV1GeneratePoemV1Post = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generatePoemV1GeneratePoemV1Post>>,
      TError,
      { data: PoemV1CreateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof generatePoemV1GeneratePoemV1Post>>,
  TError,
  { data: PoemV1CreateRequest },
  TContext
> => {
  const mutationOptions =
    getGeneratePoemV1GeneratePoemV1PostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Generatepoemv2
 */
export const generatePoemV2GeneratePoemV2Post = (
  poemV2CreateRequest: PoemV2CreateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(`/generate-poem-v2`, poemV2CreateRequest, options);
};

export const getGeneratePoemV2GeneratePoemV2PostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generatePoemV2GeneratePoemV2Post>>,
    TError,
    { data: PoemV2CreateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generatePoemV2GeneratePoemV2Post>>,
  TError,
  { data: PoemV2CreateRequest },
  TContext
> => {
  const mutationKey = ["generatePoemV2GeneratePoemV2Post"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generatePoemV2GeneratePoemV2Post>>,
    { data: PoemV2CreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return generatePoemV2GeneratePoemV2Post(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GeneratePoemV2GeneratePoemV2PostMutationResult = NonNullable<
  Awaited<ReturnType<typeof generatePoemV2GeneratePoemV2Post>>
>;
export type GeneratePoemV2GeneratePoemV2PostMutationBody = PoemV2CreateRequest;
export type GeneratePoemV2GeneratePoemV2PostMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Generatepoemv2
 */
export const useGeneratePoemV2GeneratePoemV2Post = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generatePoemV2GeneratePoemV2Post>>,
      TError,
      { data: PoemV2CreateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof generatePoemV2GeneratePoemV2Post>>,
  TError,
  { data: PoemV2CreateRequest },
  TContext
> => {
  const mutationOptions =
    getGeneratePoemV2GeneratePoemV2PostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Generatepoemv3
 */
export const generatePoemV3GeneratePoemV3Post = (
  poemV3CreateRequest: PoemV3CreateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(`/generate-poem-v3`, poemV3CreateRequest, options);
};

export const getGeneratePoemV3GeneratePoemV3PostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generatePoemV3GeneratePoemV3Post>>,
    TError,
    { data: PoemV3CreateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generatePoemV3GeneratePoemV3Post>>,
  TError,
  { data: PoemV3CreateRequest },
  TContext
> => {
  const mutationKey = ["generatePoemV3GeneratePoemV3Post"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generatePoemV3GeneratePoemV3Post>>,
    { data: PoemV3CreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return generatePoemV3GeneratePoemV3Post(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GeneratePoemV3GeneratePoemV3PostMutationResult = NonNullable<
  Awaited<ReturnType<typeof generatePoemV3GeneratePoemV3Post>>
>;
export type GeneratePoemV3GeneratePoemV3PostMutationBody = PoemV3CreateRequest;
export type GeneratePoemV3GeneratePoemV3PostMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Generatepoemv3
 */
export const useGeneratePoemV3GeneratePoemV3Post = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generatePoemV3GeneratePoemV3Post>>,
      TError,
      { data: PoemV3CreateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof generatePoemV3GeneratePoemV3Post>>,
  TError,
  { data: PoemV3CreateRequest },
  TContext
> => {
  const mutationOptions =
    getGeneratePoemV3GeneratePoemV3PostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Generatepoemv4
 */
export const generatePoemV4GeneratePoemV4Post = (
  poemV4CreateRequest: PoemV4CreateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.default.post(`/generate-poem-v4`, poemV4CreateRequest, options);
};

export const getGeneratePoemV4GeneratePoemV4PostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof generatePoemV4GeneratePoemV4Post>>,
    TError,
    { data: PoemV4CreateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof generatePoemV4GeneratePoemV4Post>>,
  TError,
  { data: PoemV4CreateRequest },
  TContext
> => {
  const mutationKey = ["generatePoemV4GeneratePoemV4Post"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof generatePoemV4GeneratePoemV4Post>>,
    { data: PoemV4CreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return generatePoemV4GeneratePoemV4Post(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type GeneratePoemV4GeneratePoemV4PostMutationResult = NonNullable<
  Awaited<ReturnType<typeof generatePoemV4GeneratePoemV4Post>>
>;
export type GeneratePoemV4GeneratePoemV4PostMutationBody = PoemV4CreateRequest;
export type GeneratePoemV4GeneratePoemV4PostMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Generatepoemv4
 */
export const useGeneratePoemV4GeneratePoemV4Post = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof generatePoemV4GeneratePoemV4Post>>,
      TError,
      { data: PoemV4CreateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof generatePoemV4GeneratePoemV4Post>>,
  TError,
  { data: PoemV4CreateRequest },
  TContext
> => {
  const mutationOptions =
    getGeneratePoemV4GeneratePoemV4PostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
