/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cloud_logic_custom: [
    {
      name: 'fuzzyPoetryApi',
      endpoint: 'https://td7w3jxto1.execute-api.us-east-1.amazonaws.com/staging',
      region: 'us-east-1'
    }
  ],
  aws_appsync_graphqlEndpoint:
    'https://3xspzuyfejfungozfk2brgzcpy.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-irmy2rvbjvhgfcopfi2nwnmhom'
}

export default awsmobile
